### ISSUE TITLE
Investigate pulling stand alone pattern lab (or KSS) instance into theme, document or script

### ISSUE THREAD

**Issue by sarahjean** [acquia-pso/cog_tools#5]
**Requirements**
- Once this issue #2 is completed, we want an ability to add/include an externally maintained pattern-lab instance into the theme.
- This instance will be added via package.json file OR via the cog_tools drush command `drush gen cog` workflow - This will ask the related questions while generating the custom theme using cog_tools.
- Based on the answers from workflow OR suggested configurations in the `package.json` file, When we run `npm install` the external repo content will be downloaded and added into the theme in such a way that it can become a part of the gulp build task and build the pattern-lab instance as a part of the theme.

**Comment by vyasamit2007** [comment]
I've worked on this and decided this workflow (Specifically for Pattern-Labs):
**Workflow**
- Run the `drush gen cog` command and select PL for the question `Would you like to include the style guide?`
- Ask next qusetions related to the external pattern-lab instance:
-- Do you have an external pattern-lab instance you would like to configure with this theme? [Y]
-- Please provide a repo URL of the external instance
- Based on the information, the theme will configure the package file including the pattern-lab instance.
- Running the `npm install` will download the required packages and also downloads the pattern-lab instance.
- Write a gulp task or leverage the #2 to make sure the patternlab instance is working with gulp task.

@sarahjean Let me know if this looks good OR it require any rectification. Once you confirm I'll start the implementation of this.

Thanks!
